### ISSUE TITLE
Draw Use Case Diagram

### ISSUE THREAD

**Issue by apetros1** [gsu-swe-s2019-group-1/project#9]
Give a Use Case diagram for one of the use cases that you have for the project. For example, if you have 12 use cases for your project, you can select one of those and represent that using a use case diagram.
NOTE: You must use Microsoft Visio to draw use case diagrams.
    • Microsoft Visio should be available from the CS departments software page with Microsoft Imagine. You should be able to download your personal copy here:
      
      https://cscit.cs.gsu.edu/sp/software/start
      
    • Click on the “Microsoft Imagine Web Store” link
    • Microsoft Visio is for Windows-Only, no Mac

Refer page 146 Figure 5.5 for use case diagram. Also take a look at the following link to get a better understanding.
http://www.agilemodeling.com/artifacts/useCaseDiagram.htm

**Comment by Cdele** [comment]
GitHub doesn't support the .vsdx file so here's the PDF instead.

[Diagrams.pdf](https://github.com/gsu-swe-s2019-group-1/project/files/2852305/Diagrams.pdf)

**Comment by Cdele** [comment]
[Diagrams2.0.pdf](https://github.com/gsu-swe-s2019-group-1/project/files/2861453/Diagrams2.0.pdf)
Version 2

**Comment by flaviut** [comment]
You can definitely upload vsdx files, but you need to install a program on your computer & learn how to use git. Take a look at:

- [the official command-line git client](https://git-scm.com/downloads)
- [various GUI-based git clients](https://git-scm.com/downloads/guis)
- [Git tutorial 1](https://www.atlassian.com/git)
- [Git tutorial 2](https://try.github.io/)

Git is kinda complicated, but it's used by basically every software developer, every day.

**Comment by flaviut** [comment]
Re. the diagram:

the customer can't use the withdraw & deposit cash features of the web application because they would just use them to give themselves infinite money. Only the banker can use these features, although the cash is being withdrawn from & deposited to the user's account. Think about when you got to the bank: you don't look at the banker's computer screen and press buttons on it, the banker does that.

I think version 1 looks better: the wording is clearer, and besides the extra line on "withdraw cash" and "deposit cash", it's accurate.
